# PowerPay DigitalOcean Docker Configuration
version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: powerpay-postgres
    environment:
      POSTGRES_DB: powerpay
      POSTGRES_USER: powerpay_user
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - powerpay-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: powerpay-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - powerpay-network

  # API Backend
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile
    container_name: powerpay-api
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: powerpay
      DATABASE_USERNAME: powerpay_user
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      FLUTTERWAVE_SECRET_KEY: ${FLUTTERWAVE_SECRET_KEY}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped
    networks:
      - powerpay-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Web Application
  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
    container_name: powerpay-web
    environment:
      REACT_APP_API_URL: http://localhost:3000/api
      REACT_APP_ENVIRONMENT: production
    ports:
      - "3001:80"
    restart: unless-stopped
    networks:
      - powerpay-network

  # Admin Dashboard
  admin:
    build:
      context: ./apps/admin
      dockerfile: Dockerfile
    container_name: powerpay-admin
    environment:
      REACT_APP_API_URL: http://localhost:3000/api
      REACT_APP_ENVIRONMENT: production
    ports:
      - "3002:80"
    restart: unless-stopped
    networks:
      - powerpay-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: powerpay-nginx
    volumes:
      - ./infrastructure/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
      - web
      - admin
    restart: unless-stopped
    networks:
      - powerpay-network

networks:
  powerpay-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: