# DigitalOcean App Platform Configuration
name: powerpay
services:

# API Backend Service
- name: api
  source_dir: /apps/api
  github:
    repo: TheCyberMayor/PowerPay
    branch: master
    deploy_on_push: true
  run_command: npm run start:prod
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /api
  envs:
  - key: NODE_ENV
    value: production
  - key: NPM_CONFIG_PRODUCTION
    value: "false"
  - key: DATABASE_URL
    value: ${db.DATABASE_URL}
  - key: DATABASE_SSL
    value: "true"
  - key: QUEUES_ENABLED
    value: "false"
  - key: JWT_SECRET
    value: your-super-secure-jwt-secret-key
  - key: PAYSTACK_SECRET_KEY
    value: sk_live_your_paystack_secret_key
  - key: FLUTTERWAVE_SECRET_KEY
    value: FLWSECK-your-flutterwave-secret-key
    
# Web App Service
- name: web
  source_dir: /apps/web
  github:
    repo: TheCyberMayor/PowerPay
    branch: master
    deploy_on_push: true
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  envs:
  - key: NPM_CONFIG_PRODUCTION
    value: "false"
  - key: REACT_APP_API_URL
    value: ${api.PUBLIC_URL}/api
  - key: REACT_APP_ENVIRONMENT
    value: production
  - key: REACT_APP_PAYSTACK_PUBLIC_KEY
    value: pk_live_your_paystack_public_key

# Admin Dashboard Service  
- name: admin
  source_dir: /apps/admin
  github:
    repo: TheCyberMayor/PowerPay
    branch: master
    deploy_on_push: true
  build_command: npm run build
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /admin
  envs:
  - key: NPM_CONFIG_PRODUCTION
    value: "false"
  - key: REACT_APP_API_URL
    value: ${api.PUBLIC_URL}/api
  - key: REACT_APP_ENVIRONMENT
    value: production

# Static Assets
static_sites:
- name: assets
  source_dir: /
  github:
    repo: TheCyberMayor/PowerPay
    branch: master
    deploy_on_push: true
  routes:
  - path: /assets

# Databases
databases:
- name: db
  engine: PG
  version: "15"
  size: basic-xs

# Domain Configuration
# domains:
# - domain: powerpay.ng
#   type: PRIMARY
#   certificate_id: your-ssl-cert-id
# - domain: admin.powerpay.ng
#   type: ALIAS
# - domain: api.powerpay.ng
#   type: ALIAS