# DigitalOcean App Platform Configuration - API Only
name: powerpay
services:

# API Backend Service
- name: api
  source_dir: apps/api
  github:
    repo: TheCyberMayor/PowerPay
    branch: master
    deploy_on_push: true
  run_command: npm run start:prod
  build_command: npm ci && npm run build && ls -la dist/
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 3000
  routes:
  - path: /
  envs:
  - key: NODE_ENV
    value: production
  - key: DATABASE_URL
    value: "postgresql://placeholder"
  - key: DATABASE_SSL
    value: "true"
  - key: QUEUES_ENABLED
    value: "false"
  - key: JWT_SECRET
    value: your-super-secure-jwt-secret-key
  - key: FLUTTERWAVE_SECRET_KEY
    value: FLWSECK-your-flutterwave-secret-key
  - key: FLUTTERWAVE_PUBLIC_KEY
    value: FLWPUBK-your-flutterwave-public-key

# No managed databases - using external PostgreSQL cluster
# Database connection will be set via environment variable

# Frontend services temporarily disabled due to missing React source files
# Uncomment and re-deploy after creating complete React applications
#
# # Web App Service
# - name: web
#   source_dir: /apps/web
#   github:
#     repo: TheCyberMayor/PowerPay
#     branch: master
#     deploy_on_push: true
#   build_command: npm run build
#   environment_slug: node-js
#   instance_count: 1
#   instance_size_slug: basic-xxs
#   routes:
#   - path: /web
#   envs:
#   - key: NPM_CONFIG_PRODUCTION
#     value: "false"
#   - key: REACT_APP_API_URL
#     value: ${api.PUBLIC_URL}/api
#   - key: REACT_APP_ENVIRONMENT
#     value: production
#   - key: REACT_APP_FLUTTERWAVE_PUBLIC_KEY
#     value: FLWPUBK-your_public_key
#
# # Admin Dashboard Service  
# - name: admin
#   source_dir: /apps/admin
#   github:
#     repo: TheCyberMayor/PowerPay
#     branch: master
#     deploy_on_push: true
#   build_command: npm run build
#   environment_slug: node-js
#   instance_count: 1
#   instance_size_slug: basic-xxs
#   routes:
#   - path: /admin
#   envs:
#   - key: NPM_CONFIG_PRODUCTION
#     value: "false"
#   - key: REACT_APP_API_URL
#     value: ${api.PUBLIC_URL}/api
#   - key: REACT_APP_ENVIRONMENT
#     value: production